### ISSUE TITLE
My blog do NOT generate lazyload img in hexo generate

### ISSUE THREAD

**Issue by iChrAlpha** [hexojs/hexo-filter-lqip#87]
After I install this plugin into my hexo blog, then I add the keywords to theme's _config.

But as I clean the cache, use `hexo clean && hexo g`, it did not make any sense.

I love this idea to lazyload image so much that how can I use it up correctly.

P.S. I am actually not good at coding since I am in the mathematical domain, so may be poor in capability. Pardon.

**Comment by ertrzyiks** [comment]
Hey @ChrAlpha, this plugin does not generate any assets if that's what you expected. It also does not cover the full integration into the blog, there is a separate issue #51 to make it simpler. In the current shape, it's more like a helper that allows you to build your own lazy loading version.

To use it you need to update your theme with something similar to what is described here https://github.com/hexojs/hexo-filter-lqip#front-end-integration

You can grasp the idea how to do that also by reviewing the example blog https://github.com/ertrzyiks/hexo-lqip-example

Is your blog's source code publicly available?
